### ISSUE TITLE
Fixing colours in Fountain lexer

### ISSUE THREAD

**Issue by mangobait** [CudaText-addons/cuda_fountain_helper#2]
Notice in the attachment that the highlighted line is the same colour as the dialogue above it. Only the line directly under a character is dialogue (unless joined by character action/description in parentheses). 

For example:

LITTLE BRAVE
(confused) <--character action
Your finger? <--dialogue

Edward slips his ring off. <--character action

Right now, "Your finger?" and "Edward slips his ring off" are the same colour. But "(confused)" and "Edward slips his ring off" should be same. Both are description.

<img width="857" alt="2017-05-20 2 44 01" src="https://cloud.githubusercontent.com/assets/18215283/26278648/d9401ab0-3d6d-11e7-841c-f8334cdfa90d.png">

**Comment by Alexey-T** [comment]
Need to fix the lexer.

**Comment by Alexey-T** [comment]
Tried, saw limitation of lexer engine: cannot catch emptyline, and so 'action' after. ops.

**Comment by mangobait** [comment]
Re: our discussion of invisibles: can't you capture an instance of two
RETURN characters in a row?  That becomes an empty line. No?

**Comment by Alexey-T** [comment]
lexer reg-expression engine cannot "catch" reg-ex "^$" (empty line). It can catch "\n\n" but it wont help.

**Comment by Alexey-T** [comment]
ops, regex "\n\n" helps..... good. Trying to fix.

**Comment by Alexey-T** [comment]
Better look 
 
![fo-new](https://cloud.githubusercontent.com/assets/4154978/26282865/87ce9818-3e22-11e7-8a21-466b229cccb0.png)

Install F lexer again, pls (AddonManager)

**Comment by mangobait** [comment]
No change. It still has lines of description the same colour as lines of
dialogue.

Question: is "Update..." in AddOns the same as "Install..." for
reinstalling? I tried both and no change to the above.

**Comment by Alexey-T** [comment]
Pls try Addonmanager- install- Fountain LEXER- it must reinstall lexer

**Comment by Alexey-T** [comment]
I checked lexer, it shows dlg lines like on picture

Yes, "Update" is same as "Install"

**Comment by mangobait** [comment]
Yes, works well now.

**Comment by Alexey-T** [comment]
Ok, good..
