### ISSUE TITLE
Fountain lexer: hilite paragraphs

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_fountain_helper#3]
Todo for me.
@mangobait Your wish.

**Comment by Alexey-T** [comment]
@mangobait Is hiliting of paragraph, eg

Dialog
(act)
Dialog

really needed? seems, lexer shows all colored. why paragraph hilite needed at all?
And hiliting with BG color of current block not enough?

**Comment by mangobait** [comment]
The paragraph highlighting was a separate issue. I think it was with 
regards to a "Focus mode" where the background would go darker and the 
paragraph or sentence where the cursor was would be brighter. (Like they 
have in Ulysses, iA Writer and one Atom package.)

So it wouldn't be a Fountain issue per se. More a separate package if 
you were to do that.

**Comment by Alexey-T** [comment]
Will think about focus mode...
